dontChroot: false
timeout: 30
script:
    - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
    - "echo 'ALL_config=\"/etc/mkinitcpio.conf\"' > /etc/mkinitcpio.d/linux.preset"
    - "echo 'ALL_kver=\"/boot/vmlinuz-linux\"' >> /etc/mkinitcpio.d/linux.preset"
    - "echo 'PRESETS=(\"default\" \"fallback\")' >> /etc/mkinitcpio.d/linux.preset"
    - "echo 'default_image=\"/boot/initramfs-linux.img\"' >> /etc/mkinitcpio.d/linux.preset"
    - "echo 'fallback_image=\"/boot/initramfs-linux-fallback.img\"' >> /etc/mkinitcpio.d/linux.preset"
    - "echo 'fallback_options=\"-S autodetect\"' >> /etc/mkinitcpio.d/linux.preset"